### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lythx** [lythx/stefan#1]
- [x] wygenerowac plansze
- [x] zrobic ui pasek na dole na modele pasek na górze na status pasek na energie nad modelami, timer na pasku na górze po prawej
- [x] postawić jakikolwiek model na planszy
- [x] zrobić bazy
- [x] zrobic klase modelu i ruszanie sie po planszy
- [x] zrobic tak zeby w siebie nie wchodziły
- [x] zrobic zeby chodzily po drodze
- [x] dać im atrybuty energia, atak, hp itd
- [x] zrobic bicie sie
- [x] zrobic bicie bazy
- [x] zrobic win condition
